# Generated by Django 4.0.6 on 2023-02-10 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_repository'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('CO', 'Contributor'), ('RA', 'Repository Admin'), ('SA', 'Site Admin')], default='CO', max_length=2)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.repository')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
