# Generated by Django 4.0.6 on 2023-02-10 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_joinrequest_userrole_user_is_site_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='status',
            field=models.CharField(choices=[('UN', 'Unknown'), ('PU', 'Public')], default='UN', max_length=2),
        ),
    ]
