# Generated by Django 4.0.6 on 2023-02-10 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_repository_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_site_admin',
            field=models.BooleanField(default=False, verbose_name='site admin'),
        ),
        migrations.CreateModel(
            name='HarvestProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.URLField(max_length=255)),
                ('harvest_type', models.CharField(choices=[('F', 'File'), ('D', 'Directory'), ('S', 'Sitemap'), ('O', 'OAI-PMH')], default='F', max_length=1)),
                ('default_format', models.CharField(choices=[('E', 'EAD'), ('M', 'MARC (under development)'), ('P', 'PDF (under development)')], default='E', max_length=255)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.repository')),
            ],
        ),
    ]
