# Generated by Django 4.0.6 on 2023-03-03 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_user_is_site_admin_harvestprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvestprofile',
            name='default_format',
            field=models.CharField(choices=[('E', 'EAD'), ('M', 'MARC (under development)'), ('P', 'PDF (under development)')], default='E', max_length=1),
        ),
        migrations.CreateModel(
            name='FindingAid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('E', 'EAD'), ('M', 'MARC'), ('P', 'PDF (under development)')], default='E', max_length=1)),
                ('elasticsearch_id', models.CharField(blank=True, max_length=32)),
                ('last_update', models.DateTimeField(blank=True)),
                ('revision_notes', models.TextField(blank=True)),
                ('reference_code', models.TextField(blank=True)),
                ('title', models.TextField()),
                ('date', models.TextField(blank=True)),
                ('extent', models.TextField(blank=True)),
                ('creator', models.TextField(blank=True)),
                ('scope_and_content', models.TextField(blank=True)),
                ('governing_access', models.TextField(blank=True)),
                ('languages', models.TextField(blank=True)),
                ('rights', models.TextField(blank=True)),
                ('indent', models.TextField(blank=True)),
                ('intra_repository', models.TextField(blank=True)),
                ('level', models.CharField(blank=True, max_length=32)),
                ('creative_commons', models.CharField(blank=True, max_length=32)),
                ('custodhist', models.TextField(blank=True)),
                ('acqinfo', models.TextField(blank=True)),
                ('processinfo', models.TextField(blank=True)),
                ('container', models.TextField(blank=True)),
                ('repository_link', models.TextField(blank=True)),
                ('digital_link', models.TextField(blank=True)),
                ('scope_and_content_raw', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('abstract', models.TextField(blank=True)),
                ('citation', models.TextField(blank=True)),
                ('bioghist', models.TextField(blank=True)),
                ('originals_location', models.TextField(blank=True)),
                ('ark', models.TextField(blank=True)),
                ('snac', models.TextField(blank=True)),
                ('wiki', models.TextField(blank=True)),
                ('progenitorID', models.IntegerField(blank=True, default=0)),
                ('parentID', models.IntegerField(blank=True, default=0)),
                ('component', models.CharField(blank=True, max_length=10)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.repository')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
