# Generated by Django 4.0.6 on 2023-03-15 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_harvestprofile_default_format_findingaid'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_header', models.CharField(blank=True, max_length=255)),
                ('finding_aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.findingaid')),
            ],
        ),
        migrations.CreateModel(
            name='FindingAidAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_notes', models.CharField(blank=True, max_length=255)),
                ('update_date', models.DateField(null=True)),
                ('updated_by', models.CharField(blank=True, max_length=32)),
                ('finding_aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.findingaid')),
            ],
        ),
        migrations.CreateModel(
            name='ControlAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(blank=True, max_length=255)),
                ('link', models.CharField(blank=True, max_length=1255)),
                ('control_type', models.CharField(blank=True, max_length=1255)),
                ('finding_aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.findingaid')),
            ],
        ),
    ]
