# Generated by Django 4.0.6 on 2023-03-16 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_subjectheader_findingaidaudit_controlaccess'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='repository',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='elasticsearch_id',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='repository',
            name='email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='repository',
            name='governing_access',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='latitude',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='repository',
            name='longitude',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='repository',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='repository',
            name='po_box',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='repository',
            name='st_city',
            field=models.CharField(blank=True, max_length=255, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='repository',
            name='st_zip_code_4_following_numbers',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='repository',
            name='st_zip_code_5_numbers',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='repository',
            name='state',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='repository',
            name='street_address_1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='repository',
            name='street_address_2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='repository',
            name='street_address_county',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='repository',
            name='url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='repository',
            name='status',
            field=models.CharField(choices=[('UN', 'Unknown'), ('UV', 'Unverified'), ('PU', 'Public')], default='UN', max_length=2),
        ),
        migrations.AddField(
            model_name='repository',
            name='repository_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.repositorytype'),
        ),
    ]
