# Generated by Django 4.0.6 on 2023-03-20 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_repositorytype_repository_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FindingAidDefaults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('governing_access', models.TextField(blank=True)),
                ('rights', models.TextField(blank=True)),
                ('creative_commons', models.URLField(max_length=255)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.repository')),
            ],
        ),
        migrations.CreateModel(
            name='Chronology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=255)),
                ('event', models.CharField(blank=True, max_length=1255)),
                ('sort_order', models.IntegerField()),
                ('finding_aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.findingaid')),
            ],
        ),
    ]
