# Generated by Django 4.0.6 on 2023-03-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_findingaiddefaults_chronology'),
    ]

    operations = [
        migrations.AddField(
            model_name='findingaid',
            name='associated_file',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
